"""followers

Revision ID: 49685a504186
Revises: c7d69dc9eec6
Create Date: 2020-11-09 09:57:03.323957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49685a504186'
down_revision = 'c7d69dc9eec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
